\documentclass[french,]{compterendu}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[left=2cm,right=2cm,top=2.5cm,bottom=2.5cm]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={La popularité des musiques sur la plateforme Spotify},
            pdfauthor={Elif ERTAS},
            pdfkeywords={Spotify; Top music; Popularity},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[shorthands=off,main=french]{babel}
\else
  \usepackage{csquotes}
  \usepackage{polyglossia}
  \setmainlanguage[]{}
\fi
\usepackage[style=alphabetic]{biblatex}

\addbibresource{biblio-cr-urca.bib}
% Adding environment CSLReferences for compatibility with pandoc >= 2.8
% BEGIN

\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1 \everypar{\setlength{\hangindent}{\cslhangindent}}\ignorespaces\fi
  % set entry spacing
  \ifnum #2 > 0
  \setlength{\parskip}{#2\baselineskip}
  \fi
 }%
 {}
\usepackage{calc} % for \widthof, \maxof
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\maxof{\widthof{#1}}{\csllabelwidth}}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth}{#1}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

% END
\usepackage{longtable,booktabs}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}



%Mise en page
%\usepackage[left=2cm,right=2cm,top=2cm,bottom=2.5cm]{geometry}
%\usepackage{lastpage} %Pour numérotaion des pages
\usepackage{eso-pic} %pour l'image de fond de la page de garde
\usepackage{enumitem} %Pour personnaliser les listes à puces
\usepackage{fancyhdr}
\usepackage{xcolor}
\usepackage[T1]{fontenc}
\usepackage{amsthm}
%\usepackage{thmtools}

\usepackage[figure,table]{totalcount} % Pour avoir les nombres de figures, tables et théoremes
\usepackage{totcount} % Pour compter le nombre de références

%Gestion des tableaux
\usepackage{multirow}
\usepackage{float}
\floatplacement{table}{H}
\floatplacement{figure}{ht!}

%Divers
\usepackage{ifthen} %Gestion des instructions conditionnelles

% % Gestion de la bibliographie
% \usepackage[sorting=none, backend=biber]{biblatex}
% \addbibresource{biblio_cr-urca.bib}

\widowpenalty=10000
\clubpenalty=10000

%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Defining new counters %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Compteur des références
\newtotcounter{citenum} %From the package documentation
\def\oldbibitem{} \let\oldbibitem=\bibitem
\def\bibitem{\stepcounter{citenum}\oldbibitem}




\regtotcounter{figure}
\regtotcounter{table}
\regtotcounter{theorem}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Configuration des messages de type badbox %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\widowpenalty=10000
\clubpenalty=10000


%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Theorem environemments %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\theoremstyle{urcastyle}
\newtheorem{theorem}{Théorème}
\newtheorem{lemma}{Lemme}
\newtheorem{corollary}{Corollaire}
\newtheorem{proposition}{Proposition}
\newtheorem{definition}{Définition}
\newtheorem{example}{Exemple}

\theoremstyle{remark}
%\newtheorem*{proof}{Démonstration}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Désignation des variables de la classe %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Processing title
  \newcommand{\titlehead}{La popularité des musiques sur la plateforme Spotify}
  \title{La popularité des musiques sur la plateforme Spotify}
    % Processing authors
  \newcounter{nbaut}
  \setcounter{nbaut}{1} % Nombre d'auteurs
  \author{Elif ERTAS}
      \date{25 avril 2023}

 \resume{À partir d'une base de donnée provenant directement de la plateforme Spotify, on veut expliquer la popularité des musiques. \newline On étudiera donc le phénomène à travers différentes variables tel que le type de groupe, la danceabilité et l'acoustique.}
 \keywords{Spotify, Top music, Popularity.}

 \gitrepo{\url{https://github.com/pregnault/urcadown}}
 \database{\url{http://organizeyourmusic.playlistmachinery.com}}


 \coefficient{50 \%}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}

  \email{\href{mailto:elif.ertas@etudiant.univ-reims.fr}{\nolinkurl{elif.ertas@etudiant.univ-reims.fr}}}
%\email{\href{mailto:elif.ertas@etudiant.univ-reims.fr}{\nolinkurl{elif.ertas@etudiant.univ-reims.fr}}}
\logouniv{logo_URCA.pdf}
\logoufr{logoSEN.pdf}
\date{25 avril 2023}
\diplome{Master statistique pour l'évaluation et prévision, 1\up{ère} année}
\anac{2022-2023}
\module{SEP0831}
\enseig{Philippe Regnault}
\evaluation{Compte-rendu d'analyse}

%% Passage des compteurs à la classe pour maketitle.
\totfig{\total{figure}}
\tottab{\total{table}}
\totref{\total{citenum}}
\tottheo{\total{theorem}}

%%%%%%%%%%%%%%%%%%%
%% Mise en forme %%
%%%%%%%%%%%%%%%%%%%


%Formatage en-têtes et pieds de pages
\pagestyle{fancy}
\fancyhead[L]{\small \titlehead}
%\fancyhead[C]{\small \textcolor{urcabrown}{\titlehead}}
\fancyhead[R]{}
\fancyfoot[l]{\small \ifnum \value{nbaut}=1 {Elif ERTAS} \else {Elif ERTAS \textit{et al.}}\fi}
\fancyfoot[C]{\small \it \theeval \ \themodule \ -- \theanac}
\fancyfoot[R]{\small \thepage\ / \pageref{LastPage}}
% \renewcommand{\headrule}{\hbox to\headwidth{%
%     \color{urcabrown}\leaders\hrule height \headrulewidth\hfill}}
% \renewcommand{\footrule}{\hbox to\headwidth{%
%     \color{urcabrown}\leaders\hrule height \headrulewidth\hfill}}
\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}

\renewcommand{\headrulewidth}{0.5pt}
\renewcommand{\footrulewidth}{0.5pt}

\fancypagestyle{plain}{%
\fancyhf{} % clear all header and footer fields
\fancyfoot[C]{\small \thepage\ / \pageref{LastPage}} % except the center
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}}

\AtEndDocument{\thispagestyle{plain}}
% Pandoc header
  \usepackage{booktabs}
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{multirow}
  \usepackage{wrapfig}
  \usepackage{float}
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage{threeparttablex}
  \usepackage[normalem]{ulem}
  \usepackage{makecell}
  \usepackage{xcolor}


%%%%%%%%%%%%%%%%%%%%%%%
%% Début du document %%
%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

\AddToShipoutPictureBG*{\includegraphics[width=\paperwidth,height=\paperheight]{fond_a4_sen_3.pdf}}

% \theoremstyle{urca}
\newtheorem{lemme}{Lemme}[section]
\newtheorem{theoreme}{Théorème}[section]
% \newtheorem{proposition}{Proposition}[section]
% \newtheorem{definition}{Définition}[section]
\newtheorem{corollaire}{Corollaire}[section]
\newtheorem{propriete}{Propriété}[section]
\newtheorem{proprietes}{Propriétés}[section]



\maketitle

% \pagebreak
% 
% % \begin{abstract}
% À partir d'une base de donnée provenant directement de la plateforme Spotify, on veut expliquer la popularité des musiques. \newline On étudiera donc le phénomène à travers différentes variables tel que le type de groupe, la danceabilité et l'acoustique.
% \end{abstract}
% 

% \vspace{1cm}
% 
% Test afficher le nombre de citations : \total{citenum}

\newpage

  {
  \hypersetup{linkcolor=black}
  \setcounter{tocdepth}{2}
  \tableofcontents
  }

\pagebreak
\normalsize



\hypertarget{description-des-donnuxe9es}{%
\section{Description des données}\label{description-des-donnuxe9es}}

\hypertarget{la-plateforme-de-streaming-spotify}{%
\subsection{La plateforme de streaming Spotify}\label{la-plateforme-de-streaming-spotify}}

Depuis des décennies, la musique se trouve partout dans notre quotidien, encore plus aujourd'hui avec toutes les nouvelles technologies et en particulier les réseaux sociaux. Il existe une multitude de plateformes de streaming musical dans lesquelles on peut découvrir des musiques du monde entier. Cependant, il y a toujours des musiques plus populaires que d'autres, d'ailleurs les classements peuvent être très différents d'un pays à l'autre. La culture musicale peut varier d'une zone à l'autre, c'est donc pour cela que notre étude se fera uniquement sur le classement mondial des musiques. Spotify est l'un des services de streaming musical les plus connues, cette plateforme permet une écoute instantanée de diverses musiques. De plus, c'est une plateforme gratuite, ce qui permet d'avoir encore plus d'utilisateurs. La plateforme compte aujourd'hui plus de 500 millions d'utilisateurs mensuels, répartis dans le monde entier et de tout âge.

\hypertarget{lobjectif-de-luxe9tude}{%
\subsection{L'objectif de l'étude}\label{lobjectif-de-luxe9tude}}

La présente étude vise à mettre en évidence l'impact de divers facteurs sur la popularité d'une musique dans le top 100 annuel mondial sur la plateforme de streaming Spotify. Précisément, on cherche à identifier des différences significatives de la popularité entre le type de groupe, la danceabilité ou l'acoustique d'une musique.

\hypertarget{les-donnuxe9es-utilisuxe9es}{%
\subsection{Les données utilisées}\label{les-donnuxe9es-utilisuxe9es}}

Cette étude est possible grâce à une base de données\footnote{Il s'agit de données officielles, issues directement de la plateforme Spotify.} regroupant les 100 meilleures musiques de chaque année entre 2010 et 2019 ce qui nous fait un total de 1000 musiques. Cette base de données provient d'un site appartenant à Spotify\footnote{\url{http://organizeyourmusic.playlistmachinery.com/} la base de donnée est constituée automatiquement en précisant pour quelle(s) playlist(s) de la plateforme Spotify vous voulez extraire les informations.} qui permet de récolter les informations de n'importe quelles musiques sur leur plateforme.

Précisèment, parmi les informations (variables) recueillies, citons\footnote{Il y a d'autres variables présentes dans la base de données qui ne sont pas citées car elles ne nous intéressent pas, voir l'annexe 1 pour plus d'informations.} :

\begin{itemize}
\tightlist
\item
  \texttt{title} : le titre de la musique (on y trouve également le nom des collaborateurs s'il y en a) ;
\item
  \texttt{artist} : Le nom de l'artiste ou du groupe principal qui interprète la musique ;
\item
  \texttt{top\_genre} : Le genre dominant de la musique (ici 132 genres differents) ;
\item
  \texttt{bpm} : Le nombre de battements par minute (=tempo) ;
\item
  \texttt{nrgy} : L'énergie de la musique (de 0 à 100, plus elle est élevée et plus la musique est énergétique) ;
\item
  \texttt{dnce} : La danceabilité de la musique (de 0 à 100, plus elle est élevée et plus il est facile de danser) ;
\item
  \texttt{val} : La valence de la musique (de 0 à 100, plus elle est élevée et plus la musique est joyeuse) ;
\item
  \texttt{acous} : L'acoustique de la musique (de 0 à 100) ;
\item
  \texttt{pop} : La popularité de la musique sur la plateforme Spotify (de 0 à 100) ;
\item
  \texttt{artist\_type} : Le type d'artiste, c'est-à-dire en Solo, Duo, Trio ou Groupe ;
\end{itemize}

\hypertarget{les-diffuxe9rents-types-dartistes}{%
\section{Les différents types d'artistes}\label{les-diffuxe9rents-types-dartistes}}

\hypertarget{la-ruxe9partition-des-types-dartistes}{%
\subsection{La répartition des types d'artistes}\label{la-ruxe9partition-des-types-dartistes}}





\begin{figure}[ht!]

{\centering \includegraphics{ERTAS_ELIF-CR_SEP0831_files/figure-latex/RepartArtiste-1} 

}

\caption{Répartition des types d'artistes. \newline
\textbf{Cohorte :} L'ensemble des 1000 musiques de la base de données. \newline
\textbf{Lecture :} On observe que le type d'artiste qui domine est le Solo à 74.8\% suivi par le type Groupe à 16.9\%, le type Duo à 7\% puis pour finir les trio à 1.3\%}\label{fig:RepartArtiste}
\end{figure}

Le type d'artiste qui domine est le soliste, cette dominance est dû en particulier aux nombreuses collaborations entre artistes. En effet le type ``Solo'' prend en compte les titres de musiques faites par un seul interprète tel que Rihanna mais aussi les titres de musiques faites en collaboration où l'artiste principal est un Solo tel que ``Sucker for Pain'' qui est un titre de Lil Wayne (Solo) en collaboration avec Wiz Khalifa (Solo), Imagine Dragons (Groupe de 4) et d'autres artistes. En général, ce sont les artistes solo qui font le plus de collaborations.

\hypertarget{la-popularituxe9-entre-les-diffuxe9rents-types-dartistes}{%
\subsection{La popularité entre les différents types d'artistes}\label{la-popularituxe9-entre-les-diffuxe9rents-types-dartistes}}

En février 2021, le site \textbf{Europavox} sort publiait un article\footnote{\url{https://www.europavox.com/fr/news/how-the-featured-artist-is-excelling-across-europe/}} \autocite{ferreira_amorim_abiassi_collaborations_2021} faisant écho que les artistes solo auraient tendance à produire des chansons plus populaires que les groupes, notamment grâce aux nombreuses collaborations qui ont énormément du succès. Cette popularité serait dû aux mélanges des genres musicales et donc une manière d'atteindre un nouveau public pour tous les collaborateurs du titre de musique.





\begin{figure}[ht!]

{\centering \includegraphics{ERTAS_ELIF-CR_SEP0831_files/figure-latex/PopArtisteType-1} 

}

\caption{Popularité des musiques en fonction de leurs types d'artiste.\newline
\textbf{Cohorte :} L'ensemble des 1000 musiques de la base de données. \newline
\textbf{Lecture :} On observe une moyenne de 75 de popularité pour les Groupes.}\label{fig:PopArtisteType}
\end{figure}

On observe pas de grosses différences entre chaque type d'artiste comme décrit\footnote{Il y a 13 titres qui sortent de la normal pour le type Solo, ce qui signifique qu'il y a 13 titres de musique d'artistes solo qui ont une popularité nettement plus faible que les autres. On a une moyenne assez similaire les unes aux autres. De plus on observe un défaut de symétrie pour le type d'artiste Trio.} par la figure \ref{fig:PopArtisteType}.

Après analyses et résultats des tests\footnote{Des tests de normalité ont été réalisé dans la partie \ref{TestNorm1} ; un test d'égalité des variances dans la partie \ref{TestVar1} ; un test de comparaison des médianes dans la partie \ref{TestMed1} ; une comparaison des groupes deux à deux dans la partie \ref{Comp1} ;}, on a une tendance de popularité élevée dans les Groupes et Solo par rapport à Duo mais on ne peut se prononcer entre Groupe et Solo au vu de nos données.
On suppose que la non-significativité\footnote{Le niveau de significativité de tous les tests effectués a été fixé à 5\%.} avec le groupe Trio est dû au manque de données (1.3\% pour Trio)

On conclut qu'il y a bien une différence de popularité entre les types d'artistes, cependant on ne peut pas dire si un type est significativement plus populaire que tous les autres types.

\hypertarget{la-danceabilituxe9-des-musiques}{%
\section{La danceabilité des musiques}\label{la-danceabilituxe9-des-musiques}}

La danceabilité est mesurée à l'aide d'algorithmes d'analyse de la musique. Les plateformes de streaming de musique, comme Spotify, utilisent des algorithmes d'apprentissage automatique pour calculer la danceabilité des morceaux de musique en fonction de diverses caractéristiques, telles que le tempo, le rythme, la densité de la batterie et la stabilité rythmique. Les algorithmes de calcul de la danceabilité sont entraînés sur des données d'analyse musicale et peuvent être affinés en fonction des préférences des auditeurs, en utilisant des données d'écoute et des commentaires sur la musique. \newline
La danceabilité est une mesure importante pour les DJ et les producteurs de musique, car elle leur permet de sélectionner des morceaux qui feront danser le public. Elle est également utilisée par les analystes de données pour comprendre les préférences des auditeurs et pour recommander des morceaux similaires en fonction de la danceabilité. \newline
On peut alors se demander si la popularité des musiques n'est pas dû à leur danceabilité. En effet, dans notre quotidien, on entend plus souvent des musiques qui donnent envie de danser, que ce soit à la radio, à la télévision ou sur les réseaux sociaux. Cependant, ce n'est qu'un environnement propre à soi même, donc il n'y a pas d'étude ou d'article visant à imposé que la popularité d'une musique est impactée majoritairement par sa danceabilité. Elle peut tout de même avoir un rôle important, c'est ce que nous allons étudier.

\hypertarget{la-popularituxe9-des-musiques-en-fonction-de-leur-danceabilituxe9}{%
\subsection{La popularité des musiques en fonction de leur danceabilité}\label{la-popularituxe9-des-musiques-en-fonction-de-leur-danceabilituxe9}}





\begin{figure}[ht!]

{\centering \includegraphics{ERTAS_ELIF-CR_SEP0831_files/figure-latex/popdnce-1} 

}

\caption{Popularité des musiques en fonction de leur danceabilité.
\textbf{Cohorte :} L'ensemble des 1000 musiques de la base de données.
\textbf{Lecture :} Un titre de musique avec 80 de danceabilité a environ 75 de popularité.}\label{fig:popdnce}
\end{figure}

Par la figure \ref{fig:popdnce} on n'observe aucune relation particulière entre la popularité et la danceability.
Après plusieurs tests\footnote{Un test de normalité a été réalisé dans la partie \ref{TestNorm2} ; des tests de non-corrélation monotone sont réalisés dans la partie \ref{TestCor2} ;} on conclut qu'il y a existence d'une relation monotone de dépendance entre la popularité et la danceabilité

\hypertarget{lacoustique-des-musiques}{%
\section{L'acoustique des musiques}\label{lacoustique-des-musiques}}

L'acoustique d'une musique se réfère aux caractéristiques sonores de la musique, telles que le timbre, le tempo, la hauteur, le rythme, le loudness, la durée et l'énergie sonore. Ces caractéristiques sonores peuvent être utilisées pour identifier le genre musical, le style de production ou l'instrumentation de la musique. Par exemple, une musique acoustique est généralement jouée avec des instruments acoustiques, tels que la guitare acoustique, la contrebasse, le piano acoustique ou la batterie acoustique. En revanche, une musique électronique est souvent produite à l'aide de synthétiseurs, de boîtes à rythmes et d'autres équipements électroniques. L'acoustique d'une musique peut être mesurée à l'aide d'algorithmes d'analyse acoustique, qui peuvent quantifier différentes caractéristiques sonores de la musique.

\hypertarget{la-popularituxe9-des-musiques-en-fonction-de-leur-acoustique}{%
\subsection{La popularité des musiques en fonction de leur acoustique}\label{la-popularituxe9-des-musiques-en-fonction-de-leur-acoustique}}





\begin{figure}[ht!]

{\centering \includegraphics{ERTAS_ELIF-CR_SEP0831_files/figure-latex/popacous-1} 

}

\caption{Popularité des musiques en fonction de leur acoustique.
\textbf{Cohorte :} L'ensemble des 1000 musiques de la base de données.
\textbf{Lecture :} Un titre de musique avec 80 d'acoustique a environ 80 de popularité.}\label{fig:popacous}
\end{figure}

Par la figure \ref{fig:popacous} on n'observe aucune relation particulière entre la popularité et l'acoustique.
Après plusieurs tests\footnote{Un test de normalité a été réalisé dans la partie \ref{TestNorm3} ; des tests de non-corrélation monotone sont réalisés dans la partie \ref{TestCor3} ;} on conclut qu'il y a existence d'une relation monotone de dépendance entre la popularité et la danceabilité

\hypertarget{pour-aller-plus-loin}{%
\section{Pour aller plus loin}\label{pour-aller-plus-loin}}

Il serait intéressant de collecter ces données pour un seul artiste, en ayant quand même plusieurs dizaines de titres pour avoir des résultats concluant. On pourrait alors s'intéresser à cet artiste et comprendre pourquoi certains de ses titres sont plus ou moins populaires que d'autres. \newline
On pourrait également collecter ces données pour un genre de musique en particulier comme le hip-hop par exemple, on aurait des titres de musiques du même environnement. On pourrait les prendre avec des dates de sortie rapprochées pour observer s'il y a un système de concurrence mis en avant et comprendre pourquoi tel titre est plus populaire qu'un autre.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

Pour conclure, nous avons mis en évidence que la popularité d'une musique ne peut être expliqué dans sa globalité pour cette cohorte de titres de musiques. Des musiques avec des caractéristiques complétement différentes peuvent se trouver au même seuil de popularité. Une musique n'est donc pas vraiment populaire par son nombre d'interprète, son acoustique ou sa danceabilité. On peut alors toujours se demander comment
une musique peut être populaire ? Il y a un effet de mode et le partage exerce également une forte
influence sur la popularité d'une musique. On a par exemple le réseau social TikTok qui a permis à des
milliers de titres de musiques de revenir à la mode ou même de nouvelles musiques à devenir connues.

\hypertarget{remerciements}{%
\section*{Remerciements}\label{remerciements}}
\addcontentsline{toc}{section}{Remerciements}

Merci à M. Regnault pour son enseignement et ses conseils.

\hypertarget{appendix-annexes}{%
\appendix}


\hypertarget{annexes}{%
\section{Annexes}\label{annexes}}

\hypertarget{structure-de-la-base-de-donnuxe9e}{%
\subsection{Structure de la base de donnée}\label{structure-de-la-base-de-donnuxe9e}}

\begin{verbatim}
'data.frame':   1000 obs. of  17 variables:
 $ title        : chr  "STARSTRUKK (feat. Katy Perry)" "My First Kiss (feat. Ke$ha)" "I Need A Dollar" "Airplanes (feat. Hayley Williams of Paramore)" ...
 $ artist       : chr  "3OH!3" "3OH!3" "Aloe Blacc" "B.o.B" ...
 $ top_genre    : chr  "dance pop" "dance pop" "pop soul" "atl hip hop" ...
 $ year_released: num  2009 2010 2010 2010 2010 ...
 $ added        : chr  "2022‑02‑17" "2022‑02‑17" "2022‑02‑17" "2022‑02‑17" ...
 $ bpm          : num  140 138 95 93 104 82 128 92 146 109 ...
 $ nrgy         : num  81 89 48 87 85 93 81 52 59 84 ...
 $ dnce         : num  61 68 84 66 69 55 82 60 50 64 ...
 $ dB           : num  -6 -4 -7 -4 -6 -4 -8 -7 -5 -5 ...
 $ live         : num  23 36 9 4 9 35 60 31 11 6 ...
 $ val          : num  23 83 96 38 74 79 44 41 8 42 ...
 $ dur          : num  203 192 243 180 268 196 308 258 218 221 ...
 $ acous        : num  0 1 20 11 39 1 7 18 51 1 ...
 $ spch         : num  6 8 3 12 5 34 7 37 3 4 ...
 $ pop          : num  70 68 72 80 79 71 75 71 87 86 ...
 $ top_year     : num  2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 ...
 $ artist_type  : chr  "Duo" "Duo" "Solo" "Solo" ...
\end{verbatim}

\hypertarget{TestNorm1}{%
\subsection{Tests de normalité entre le type d'artiste et la popularité}\label{TestNorm1}}

\begin{verbatim}
$`Band/Group`

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.96646, p-value = 0.000419


$Duo

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.96296, p-value = 0.03656


$Solo

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.94814, p-value = 1.552e-15


$Trio

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.78376, p-value = 0.0044
\end{verbatim}

\begin{verbatim}
$`Band/Group`

    Jarque-Bera Normality Test

data:  X[[i]]
JB = 21.918, p-value = 1.74e-05
alternative hypothesis: greater


$Duo

    Jarque-Bera Normality Test

data:  X[[i]]
JB = 7.3038, p-value = 0.02594
alternative hypothesis: greater


$Solo

    Jarque-Bera Normality Test

data:  X[[i]]
JB = 216.18, p-value < 2.2e-16
alternative hypothesis: greater


$Trio

    Jarque-Bera Normality Test

data:  X[[i]]
JB = 13.465, p-value = 0.001191
alternative hypothesis: greater
\end{verbatim}

\begin{verbatim}
$`Band/Group`

    Anderson-Darling normality test

data:  X[[i]]
A = 1.1928, p-value = 0.004006


$Duo

    Anderson-Darling normality test

data:  X[[i]]
A = 0.52667, p-value = 0.1733


$Solo

    Anderson-Darling normality test

data:  X[[i]]
A = 7.6109, p-value < 2.2e-16


$Trio

    Anderson-Darling normality test

data:  X[[i]]
A = 0.94665, p-value = 0.01139
\end{verbatim}

D'après le test de Anderson-Darling le type d'artiste Duo a une p-value de 0.1733 \textgreater{} 0.05 donc on accepterait l'hypothèse de normalité pour ce type. Or il suffit qu'un test pour un seul type rejette l'hypothèse pour faire la procédure non paramètrique :
Tout les groupes ont une une p-value significative dans au moins un des tests, ici les types Group, Trio et Solo rejette l'hypothèse de normalité dans tout les tests effectués. Le type Duo rejette l'hypothèse de normalité d'après les tests de Shapiro-Wilk et Jarque-Berra
On rejette donc l'hypothèse de normalité pour tous les types.

\hypertarget{TestVar1}{%
\subsection{Test de l'égalité des variances entre le type d'artiste et la popularité}\label{TestVar1}}

\begin{verbatim}

    Fligner-Killeen test of homogeneity of variances

data:  pop by artist_type
Fligner-Killeen:med chi-squared = 3.6607, df = 3, p-value = 0.3005
\end{verbatim}

On a une p-value = 0.3005 \textgreater{} 0.05 non significative donc on accepte l'égalité des variances

\hypertarget{TestMed1}{%
\subsection{Test de comparaison des médianes entre le type d'artiste et la popularité}\label{TestMed1}}

\begin{verbatim}

    Kruskal-Wallis rank sum test

data:  pop by artist_type
Kruskal-Wallis chi-squared = 11.319, df = 3, p-value = 0.01012
\end{verbatim}

On a une p-value = 0.01012 significative donc on va devoir comparer deux-à-deux les groupes.

\hypertarget{Comp1}{%
\subsection{Comparaison deux à deux des groupes entre le type d'artiste et la popularité}\label{Comp1}}

\begin{verbatim}
# A tibble: 6 x 6
  group1     group2           p p.adj p.format p.signif
  <chr>      <chr>        <dbl> <dbl> <chr>    <chr>   
1 Duo        Solo       0.00598 0.036 0.0060   **      
2 Duo        Band/Group 0.00970 0.058 0.0097   **      
3 Duo        Trio       0.807   1     0.8067   ns      
4 Solo       Band/Group 0.631   1     0.6311   ns      
5 Solo       Trio       0.0597  0.36  0.0597   ns      
6 Band/Group Trio       0.0646  0.39  0.0646   ns      
\end{verbatim}

On observe une significativité entre Duo - Solo et Duo - Group. On en conclut que la popularité pour le type Solo est significativement plus grande que pour le type Duo et que la popularité pour le type Groupe est significativement plus grande pour que pour le type Duo

\hypertarget{TestNorm2}{%
\subsection{Test de normalité entre la danceabilité et la popularité}\label{TestNorm2}}

\begin{verbatim}

    Shapiro-Wilk normality test

data:  Z
W = 0.95874, p-value = 3.501e-16
\end{verbatim}

p-value = 3.50e-16 \textless{} 0.05 significative donc on rejette l'hypothèse de normalité

\hypertarget{TestCor2}{%
\subsection{Tests de non-corrélation monotone entre la danceabilité et la popularité}\label{TestCor2}}

\begin{verbatim}

    Kendall's rank correlation tau

data:  Spotify$pop and Spotify$dnce
z = 2.7651, p-value = 0.005691
alternative hypothesis: true tau is not equal to 0
sample estimates:
       tau 
0.06005483 
\end{verbatim}

\begin{verbatim}
Warning in cor.test.default(Spotify$pop, Spotify$dnce, method = "spearman"):
Impossible de calculer la p-value exacte avec des ex-aequos
\end{verbatim}

\begin{verbatim}

    Spearman's rank correlation rho

data:  Spotify$pop and Spotify$dnce
S = 152104509, p-value = 0.005696
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
0.08737204 
\end{verbatim}

p-value singificative pour les deux tests

\hypertarget{TestNorm3}{%
\subsection{Test de normalité entre l'acoustique et la popularité}\label{TestNorm3}}

\begin{verbatim}

    Shapiro-Wilk normality test

data:  Z
W = 0.8955, p-value < 2.2e-16
\end{verbatim}

p-value \textless{} 2.2e-16 \textless{} 0.05 significative donc on rejette l'hypothèse de normalité

\hypertarget{TestCor3}{%
\subsection{Tests de non-corrélation monotone entre l'acoustique et la popularité}\label{TestCor3}}

\begin{verbatim}

    Kendall's rank correlation tau

data:  Spotify$pop and Spotify$acous
z = 4.8058, p-value = 1.542e-06
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.1057238 
\end{verbatim}

\begin{verbatim}
Warning in cor.test.default(Spotify$pop, Spotify$acous, method = "spearman"):
Impossible de calculer la p-value exacte avec des ex-aequos
\end{verbatim}

\begin{verbatim}

    Spearman's rank correlation rho

data:  Spotify$pop and Spotify$acous
S = 141546595, p-value = 1.688e-06
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.1507196 
\end{verbatim}

p-value singificative pour les deux tests



\pagebreak
\addcontentsline{toc}{section}{Bibliographie}
\printbibliography[title={Bibliographie}, nottype=online, nottype=manual]
\printbibliography[title={Webographie}, type=online]
\printbibliography[title={Packages référencés}, type=manual]


\end{document}
